### PR TITLE
Added ZPG-Listing-ETag header and instructions on generating the .pem

### PR DESCRIPTION
**Pull request by richardjellis**

### CODE REVIEW

**Comment by jamoir** [comment]
Hi Richard,

Wish I had read your commits before trying to use this. Well done for updating the repo though.

I managed to get there in the end but I'm not getting any response from the server.

Are you doing anything different to his examples for:

$branch = new BranchObject();
        $branch->setBranchReference(Zend_Registry::get('env')->zoopla->branch_id);

        $pathToZpgCert = realpath('../certificates/zoopla/'.Zend_Registry::get('env')->zoopla->certificate_file);
        
        $method = new ListingMethod($pathToZpgCert);
        $response = $method->getList($branch);
        
        print_r(($response));

I get a GuzzleHttp response object but nothing from zoopla's response. As far as I can see.

Thanks,
Jamie

**Comment by richardjellis** [comment]
No, the example is correct in this case.

I am able to access the returned listings using something like this:

```
$response = $method->getList($branch);
$json = json_decode($response->getBody());
$listings=$json->listings;


foreach ($listings as $listing) {
    echo $listing->listing_reference . ': ' . $listing->url . ';
}
```

Make sure you are using the same branch ID for getList() that you used to post the listings.

**Comment by jamoir** [comment]
Thats really helpful Richard, thanks. You've saved me a few hours here!

**Comment by pedrosik** [comment]
hi Guys,
what about this PR? looks good and `ZPG-Listing-ETag` is required by Zoopla!

@lukeocodes can you merge it?

**Comment by lukeocodes** [comment]
@richardjellis thanks for the PR and @pedrosik thanks for nudging me. Sorry I didn't spot this!

**Comment by pedrosik** [comment]
Hi @lukeocodes, 
can you create a new tag also?

**Comment by lukeocodes** [comment]
Done v0.1.2 @ https://github.com/lukeocodes/zpg-rtf-php/commit/c7a38a85650ad76ec64eb1b1baa862448365d76f 👍

**Pull request merged**
